### ISSUE TITLE
[mawk vs gawk] regular expression compile failed (missing operand)

### ISSUE THREAD

**Issue by antonkratz** [nicolas-bertin/CAGEscan-Clustering#4]
I used CAGEscan-Clustering.pl under Debian. When it calls awk, it invokes mawk. This leads to an error "regular expression compile failed (missing operand)".

The assumption seems to be that awk invokes gawk. After installing gawk under Debian, gawk takes precedence over mawk. Then it works.

tl;dr: use gawk not mawk.

**Comment by charles-plessy** [comment]
This was fixed in commit 12baffab6fabda8c18540126f9b91435757515d5
